.TH "AsyncInput" 3 "2018年 六月 29日 星期五" "Version 3.0" "xlang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AsyncInput \- 异步输入接口 需要继承  

.SH SYNOPSIS
.br
.PP
.SS "Public 成员函数"
.SH "详细描述"
.PP 
异步输入接口 需要继承 
.PP
在文件 AsyncInput\&.xcs 第 6 行定义\&.
.SH "成员函数说明"
.PP 
.SS "bool dataArrives (Object own, Object context, byte  [] data)"

.PP
异步数据到达通知 
.PP
\fB参数:\fP
.RS 4
\fIown\fP 主要对象 
.br
\fIcontext\fP 实例上下文 
.br
\fIdata\fP 数据内容 
.RE
.PP
\fB返回:\fP
.RS 4
是否接受该操作 返回false 将拒绝操作 
.RE
.PP

.SS "bool deleteInstance (Object own, Object context)"

.PP
实例删除通知 
.PP
\fB参数:\fP
.RS 4
\fIown\fP 主要对象 
.br
\fIcontext\fP 实例上下文 
.RE
.PP
\fB返回:\fP
.RS 4
是否接受该操作 返回false 将拒绝操作 
.RE
.PP

.SS "bool inactiveTimeoutVerify (Object own, Object context)"

.PP
实例超时通知 
.PP
\fB参数:\fP
.RS 4
\fIown\fP 主要对象 
.br
\fIcontext\fP 实例上下文 
.RE
.PP
\fB返回:\fP
.RS 4
是否接受该操作 返回false 将拒绝操作 
.RE
.PP

.SS "bool newInstance (Object own, int type, long bind, Object context)"

.PP
新实例创建回调 
.PP
\fB参数:\fP
.RS 4
\fIown\fP 主要对象 
.br
\fItype\fP 操作类型 
.br
\fIbind\fP 绑定的id 
.br
\fIcontext\fP 实例上下文 
.RE
.PP
\fB返回:\fP
.RS 4
是否接受该操作 返回false 将拒绝操作 
.RE
.PP

.SS "void notify (Object own, int type, long bind, bool bsucceed, Object context, int length)"

.PP
通知回调函数 
.PP
\fB参数:\fP
.RS 4
\fIown\fP 主要对象 
.br
\fItype\fP 操作类型 
.br
\fIbind\fP 绑定的id 
.br
\fIbsucceed\fP 处理结果 
.br
\fIcontext\fP 实例上下文 
.br
\fIlength\fP 处理的长度 
.RE
.PP
\fB返回:\fP
.RS 4
提交结果 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 xlang 的 源代码自动生成\&.
