.TH "Base64" 3 "2018年 六月 29日 星期五" "Version 3.0" "xlang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Base64 \- base64类  

.SH SYNOPSIS
.br
.PP
.SS "静态包函数"
.SH "详细描述"
.PP 
base64类 
.PP
在文件 Base64\&.xcs 第 6 行定义\&.
.SH "成员函数说明"
.PP 
.SS "static byte [] decodeString (\fBString\fP text)\fC [static]\fP, \fC [package]\fP"

.PP
将base64串还原为数据 
.PP
\fB参数:\fP
.RS 4
\fItext\fP 待还原的串 
.RE
.PP
\fB异常:\fP
.RS 4
\fINullPointerException\fP 空指针异常 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static \fBString\fP encodeToString (byte   [] data, bool warp)\fC [static]\fP, \fC [package]\fP"

.PP
将数据转换为base64串 
.PP
\fB参数:\fP
.RS 4
\fIdata\fP 待转换的数据 
.br
\fIwarp\fP 是否换行 
.RE
.PP
\fB异常:\fP
.RS 4
\fINullPointerException\fP 空指针异常 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static \fBString\fP encodeToString (byte   [] data, int pos, int len, bool warp)\fC [static]\fP, \fC [package]\fP"

.PP
将数据转换为base64串 
.PP
\fB参数:\fP
.RS 4
\fIdata\fP 待转换的数据  起始位置  转换长度 
.br
\fIwarp\fP 是否换行 
.RE
.PP
\fB异常:\fP
.RS 4
\fINullPointerException\fP 空指针异常 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 xlang 的 源代码自动生成\&.
