.TH "Map<_K,  _V>.Iterator<_K,  _V>" 3 "2018年 六月 29日 星期五" "Version 3.0" "xlang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map<_K,  _V>.Iterator<_K,  _V> \- map的迭代器对象  

.SH SYNOPSIS
.br
.PP
.SS "包函数"
.SH "详细描述"
.PP 
map的迭代器对象 
.PP
在文件 Map\&.xcs 第 11 行定义\&.
.SH "成员函数说明"
.PP 
.SS "_K getKey ()\fC [package]\fP"

.PP
获取当前的key 
.SS "_V getValue ()\fC [package]\fP"

.PP
获取当前的值对象 
.SS "bool hasNext ()\fC [package]\fP"

.PP
是否有下一个 
.SS "bool hasPrevious ()\fC [package]\fP"

.PP
是否有前一个 
.SS "void next ()\fC [package]\fP"

.PP
下一个 

.SH "作者"
.PP 
由 Doyxgen 通过分析 xlang 的 源代码自动生成\&.
