.TH "Math" 3 "2018年 六月 29日 星期五" "Version 3.0" "xlang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Math \- Math类  

.SH SYNOPSIS
.br
.PP
.SS "静态包函数"
.SH "详细描述"
.PP 
Math类 
.PP
在文件 Math\&.xcs 第 6 行定义\&.
.SH "成员函数说明"
.PP 
.SS "static int abs (int v)\fC [static]\fP, \fC [package]\fP"

.PP
取绝对值 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static long abs (long v)\fC [static]\fP, \fC [package]\fP"

.PP
取绝对值 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double abs (double v)\fC [static]\fP, \fC [package]\fP"

.PP
取绝对值 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double acos (double v)\fC [static]\fP, \fC [package]\fP"

.PP
反余弦函数 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double asin (double v)\fC [static]\fP, \fC [package]\fP"

.PP
反正弦函数 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double atan (double v)\fC [static]\fP, \fC [package]\fP"

.PP
反正切函数 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double atan2 (double y, double x)\fC [static]\fP, \fC [package]\fP"

.PP
四象限反正切函数 
.PP
\fB参数:\fP
.RS 4
\fIy\fP x 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double cbrt (double v)\fC [static]\fP, \fC [package]\fP"

.PP
求立方根 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double ceil (double v)\fC [static]\fP, \fC [package]\fP"

.PP
向上取整 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double cos (double v)\fC [static]\fP, \fC [package]\fP"

.PP
余弦函数 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double cosh (double v)\fC [static]\fP, \fC [package]\fP"

.PP
双曲余弦函数 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double exp (double v)\fC [static]\fP, \fC [package]\fP"

.PP
求e为底的指数 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double expm1 (double v)\fC [static]\fP, \fC [package]\fP"

.PP
计算参数的以 e 为底的指数，减去 1 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double floor (double v)\fC [static]\fP, \fC [package]\fP"

.PP
将数字向下舍入到基数的最接近倍数 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static int floorDiv (int y, int v)\fC [static]\fP, \fC [package]\fP"

.PP
地板除 
.PP
\fB参数:\fP
.RS 4
\fIy\fP v 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static long floorDiv (long y, long v)\fC [static]\fP, \fC [package]\fP"

.PP
地板除 
.PP
\fB参数:\fP
.RS 4
\fIy\fP v 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double log (double x)\fC [static]\fP, \fC [package]\fP"

.PP
计算指定的底数的数字的对数 
.PP
\fB参数:\fP
.RS 4
\fIx\fP 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double log1p (double x)\fC [static]\fP, \fC [package]\fP"

.PP
计算1加参数以 e 为底的对数 
.PP
\fB参数:\fP
.RS 4
\fIx\fP 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static int max (int a, int b)\fC [static]\fP, \fC [package]\fP"

.PP
取最大 
.PP
\fB参数:\fP
.RS 4
\fIa\fP b 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static long max (long a, long b)\fC [static]\fP, \fC [package]\fP"

.PP
取最大 
.PP
\fB参数:\fP
.RS 4
\fIa\fP b 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double max (double a, double b)\fC [static]\fP, \fC [package]\fP"

.PP
取最大 
.PP
\fB参数:\fP
.RS 4
\fIa\fP b 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static int min (int a, int b)\fC [static]\fP, \fC [package]\fP"

.PP
取最小 
.PP
\fB参数:\fP
.RS 4
\fIa\fP b 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static long min (long a, long b)\fC [static]\fP, \fC [package]\fP"

.PP
取最小 
.PP
\fB参数:\fP
.RS 4
\fIa\fP b 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double min (double a, double b)\fC [static]\fP, \fC [package]\fP"

.PP
取最小 
.PP
\fB参数:\fP
.RS 4
\fIa\fP b 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double pow (double a, double b)\fC [static]\fP, \fC [package]\fP"

.PP
计算乘方 
.PP
\fB参数:\fP
.RS 4
\fIa\fP b 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double random ()\fC [static]\fP, \fC [package]\fP"

.PP
浮点数均匀分布随机数0~1 
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double round (double x)\fC [static]\fP, \fC [package]\fP"

.PP
四舍五入 
.PP
\fB参数:\fP
.RS 4
\fIx\fP 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double sinh (double x)\fC [static]\fP, \fC [package]\fP"

.PP
双曲正弦 
.PP
\fB参数:\fP
.RS 4
\fIx\fP 参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP

.SS "static double tanh (double v)\fC [static]\fP, \fC [package]\fP"

.PP
双曲正切函数 
.PP
\fB参数:\fP
.RS 4
\fIv\fP 输入的参数 
.RE
.PP
\fB返回:\fP
.RS 4
结果 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 xlang 的 源代码自动生成\&.
