.TH "E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/std/System.xcs" 3 "2018年 六月 29日 星期五" "Version 3.0" "xlang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/std/System.xcs \- 
.SH SYNOPSIS
.br
.PP
.SS "结构体"

.in +1c
.ti -1c
.RI "class \fB_system_\fP"
.br
.RI "\fI系统和IO相关 \fP"
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 xlang 的 源代码自动生成\&.
