.TH "E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/std/Unsi.xcs" 3 "2018年 六月 29日 星期五" "Version 3.0" "xlang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Developments/Cadaqs/caNamespace/castudio/xcross/xlang/xlang/std/Unsi.xcs \- 
.SH SYNOPSIS
.br
.PP
.SS "结构体"

.in +1c
.ti -1c
.RI "class \fBUnsi\fP"
.br
.RI "\fIunsi 通用网络服务器接口类 \fP"
.ti -1c
.RI "class \fBUnsi\&.Instance\fP"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 xlang 的 源代码自动生成\&.
