.TH "Unsi.Instance" 3 "2018年 六月 29日 星期五" "Version 3.0" "xlang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unsi.Instance \- 
.SH SYNOPSIS
.br
.PP
.SS "包函数"
.SH "详细描述"
.PP 
在文件 Unsi\&.xcs 第 8 行定义\&.
.SH "成员函数说明"
.PP 
.SS "Instance clone ()\fC [package]\fP"

.PP
克隆一个用于永久保存的实例对象 
.PP
\fB返回:\fP
.RS 4
实例对象 
.RE
.PP

.SS "bool disconnect ()\fC [package]\fP"

.PP
断开实例链接 
.PP
\fB返回:\fP
.RS 4
提交结果 
.RE
.PP

.SS "bool equals (Instance ins)\fC [package]\fP"

.PP
测试两个实例是否同一个链接 
.PP
\fB参数:\fP
.RS 4
\fIins\fP 实例对象 
.RE
.PP
\fB返回:\fP
.RS 4
是否 
.RE
.PP

.SS "int getId ()\fC [package]\fP"

.PP
获取实例编号 
.PP
\fB返回:\fP
.RS 4
编号 
.RE
.PP

.SS "int getRemoteAddress ()\fC [package]\fP"

.PP
获取远程主机地址 
.PP
\fB返回:\fP
.RS 4
32位IP地址 
.RE
.PP

.SS "int getRemotePort ()\fC [package]\fP"

.PP
获取远程主机端口 
.PP
\fB返回:\fP
.RS 4
端口号 
.RE
.PP

.SS "bool send (long sendid, byte   [] buffer, int offset, int length)\fC [package]\fP"

.PP
发送数据 
.PP
\fB参数:\fP
.RS 4
\fI识别id\fP 用于才异步输入接口的结果通知回调 
.br
\fIbuffer\fP 缓冲区 
.br
\fIoffset\fP 缓冲区的偏移量 
.br
\fIlength\fP 待发送长度 
.RE
.PP
\fB返回:\fP
.RS 4
提交结果 
.RE
.PP

.SS "bool setTimeout (int timeout)\fC [package]\fP"

.PP
设置实例链接的超时时间 
.PP
\fB返回:\fP
.RS 4
提交结果 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 xlang 的 源代码自动生成\&.
