.TH "Vector<_V>" 3 "2018年 六月 29日 星期五" "Version 3.0" "xlang" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector<_V> \- vector容器  

.SH SYNOPSIS
.br
.PP
.SS "包函数"
.SH "详细描述"
.PP 
vector容器 
.PP
在文件 Vector\&.xcs 第 7 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "\fBVector\fP (int presize)\fC [package]\fP"

.PP
构造 
.PP
\fB参数:\fP
.RS 4
\fIpresize\fP 预备大小 
.RE
.PP

.SH "成员函数说明"
.PP 
.SS "void add (_V val)\fC [package]\fP"

.PP
插入数据 
.PP
\fB返回:\fP
.RS 4

.RE
.PP

.SS "void clear ()\fC [package]\fP"

.PP
清空容器 
.PP
\fB返回:\fP
.RS 4

.RE
.PP

.SS "_V get (int pos)\fC [package]\fP"

.PP
获取指定位置的对象 
.PP
\fB参数:\fP
.RS 4
\fIpos\fP 位置序号 
.RE
.PP

.SS "void remove (int pos)\fC [package]\fP"

.PP
删除指定位置的数据 
.PP
\fB参数:\fP
.RS 4
\fIpos\fP 位置序号 
.RE
.PP
\fB返回:\fP
.RS 4
.RE
.PP

.SS "int size ()\fC [package]\fP"

.PP
获取容器内数据数量 
.PP
\fB返回:\fP
.RS 4
长度 
.RE
.PP


.SH "作者"
.PP 
由 Doyxgen 通过分析 xlang 的 源代码自动生成\&.
