#xlang makefile
#generated by XStudio http://xlang.link

CC = xlang

#编译器标志
XFLAGS = ${XFLAGS}

XCROSS = ${PLATFORM_ARCH}

OUTPUT = ${OUTPUT}

LIBPATH = ${LIBPATH}

LX = ${LX}

LIBS = ${LIBS}

SOURCES = ${SOURCES}

all:
	$(CC) $(XFLAGS) ${CMD} $(SOURCES) $(XCROSS) $(LIBPATH) $(LIBS) $(LX) -o $(OUTPUT)

clean:
	rm -rf $(OUTPUT)